
--
-- Estructura de tabla para la tabla `iso_639`
--

CREATE TABLE IF NOT EXISTS `iso_639` (
  `iso` char(2) NOT NULL,
  `english_name` varchar(64) NOT NULL,
  `native_name` varchar(64) NOT NULL,
  PRIMARY KEY (`iso`),
  UNIQUE KEY `english_name` (`english_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Language codes as defined in ISO 639-1';

--
-- Volcado de datos para la tabla `iso_639`
--

INSERT INTO `iso_639` (`iso`, `english_name`, `native_name`) VALUES
('aa', 'Afar', 'Qafara'),
('ab', 'Abkhazian', 'Аҧсуа'),
('af', 'Afrikaans', 'Afrikaans'),
('am', 'Amharic', 'አማርኛ'),
('ar', 'Arabic', 'العربية'),
('as', 'Assamese', 'অসমীয়া'),
('ay', 'Aymara', 'aymar aru'),
('az', 'Azerbaijani', 'Azərbaycanca'),
('ba', 'Bashkir', 'башҡорт теле'),
('be', 'Byelorussian', 'Беларуская мова'),
('bg', 'Bulgarian', 'Български'),
('bi', 'Bislama', 'Bislama'),
('bn', 'Bengali/Bangla', 'বাংলা'),
('bo', 'Tibetan', 'བོད་ཡིག'),
('br', 'Breton', 'brezhoneg'),
('ca', 'Catalan', 'Català'),
('co', 'Corsican', 'Corsu'),
('cs', 'Czech', 'Česky'),
('cy', 'Welsh', 'Cymraeg'),
('da', 'Danish', 'Dansk'),
('de', 'German', 'Deutsch'),
('dz', 'Dzongkha', 'རྫོང་ཁ'),
('el', 'Greek', 'Ελληνικά'),
('en', 'English', 'English'),
('eo', 'Esperanto', 'Esperanto'),
('es', 'Spanish', 'Español'),
('et', 'Estonian', 'Eesti keel'),
('eu', 'Basque', 'Euskera'),
('fa', 'Persian', 'فارسی'),
('fi', 'Finnish', 'Suomi'),
('fj', 'Fijian', 'vosa Vakaviti'),
('fo', 'Faeroese', 'føroyskt'),
('fr', 'French', 'Français'),
('fy', 'Western Frisian', 'frysk'),
('ga', 'Irish', 'Gaeilge'),
('gd', 'Scots/Gaelic', 'Gàidhlig'),
('gl', 'Galician', 'Galego'),
('gn', 'Guarani', 'Avañe''ẽ'),
('gu', 'Gujarati', 'ગુજરાતી'),
('ha', 'Hausa', ' هَوُسَ'),
('hi', 'Hindi', 'हिन्दी'),
('hr', 'Croatian', 'hrvatski jezik'),
('hu', 'Hungarian', 'Magyar'),
('hy', 'Armenian', 'Հայերեն'),
('ia', 'Interlingua', 'Interlingua'),
('ie', 'Interlingue', 'Interlingue'),
('ik', 'Inupiak', 'Iñupiaq'),
('in', 'Indonesian', 'Bahasa Indonesia'),
('is', 'Icelandic', 'íslenska'),
('it', 'Italian', 'Italiano'),
('iw', 'Hebrew', ' עברית'),
('ja', 'Japanese', '日本語'),
('ji', 'Yiddish', 'ייִדיש'),
('jw', 'Javanese', 'basa Jawa'),
('ka', 'Georgian', 'ქართული'),
('kk', 'Kazakh', 'Қазақ тілі'),
('kl', 'Greenlandic', 'kalaallisut'),
('km', 'Cambodian', 'ភាសាខ្មែរ'),
('kn', 'Kannada', 'ಕನ್ನಡ'),
('ko', 'Korean', '한국어'),
('ks', 'Kashmiri', 'कॉशुर, کٲشُر'),
('ku', 'Kurdish', 'Kurdî'),
('ky', 'Kirghiz', 'кыргыз тили'),
('la', 'Latin', 'Latinum'),
('ln', 'Lingala', 'Lingala'),
('lo', 'Laothian', 'ພາສາລາວ'),
('lt', 'Lithuanian', 'Lietuvių'),
('lv', 'Latvian/Lettish', 'Latviešu'),
('mg', 'Malagasy', 'Malagasy fiteny'),
('mi', 'Maori', 'te reo Māori'),
('mk', 'Macedonian', 'Македонски'),
('ml', 'Malayalam', 'മലയാളം'),
('mn', 'Mongolian', 'монгол хэл'),
('mr', 'Marathi', 'मराठी'),
('ms', 'Malay', 'Bahasa Melayu'),
('mt', 'Maltese', 'Malti'),
('my', 'Burmese', 'ျမန္မာစာ'),
('na', 'Nauruan', 'Ekakairũ Naoero'),
('ne', 'Nepali', 'नेपाली'),
('nl', 'Dutch', 'Nederlands'),
('no', 'Norwegian', 'Norsk'),
('oc', 'Occitan', 'Occitan'),
('om', 'Oromo', 'Afaan Oromoo'),
('pa', 'Punjabi', 'ਪੰਜਾਬੀ'),
('pl', 'Polish', 'Polski'),
('ps', 'Pashto/Pushto', 'پښتو'),
('pt', 'Portuguese', 'Português'),
('qu', 'Quechua', 'Runa Simi'),
('rm', 'Romansh', 'rumantsch grischun'),
('ro', 'Romanian', 'Română'),
('ru', 'Russian', 'Русский'),
('rw', 'Kinyarwanda', 'kinyaRwanda'),
('sa', 'Sanskrit', 'संस्कृतम्'),
('sd', 'Sindhi', 'سنڌي'),
('sg', 'Sango', 'yângâ tî sängö'),
('si', 'Singhalese', 'සිංහල'),
('sk', 'Slovak', 'slovenčina'),
('sl', 'Slovenian', 'slovenščina'),
('sm', 'Samoan', 'gagana fa''a Samoa'),
('sn', 'Shona', 'chiShona'),
('so', 'Somali', 'Soomaaliga'),
('sq', 'Albanian', 'shqip'),
('sr', 'Serbian', 'српски језик'),
('ss', 'Swati', 'siSwati'),
('st', 'Southern Sotho', 'Sesotho'),
('su', 'Sundanese', 'basa Sunda'),
('sv', 'Swedish', 'Svenska'),
('sw', 'Swahili', 'Kiswahili'),
('ta', 'Tamil', 'தமிழ்'),
('te', 'Telugu', 'తెలుగు'),
('tg', 'Tajik', 'тоҷикӣ'),
('th', 'Thai', 'ไทย'),
('ti', 'Tigrinya', 'ትግርኛ'),
('tk', 'Turkmen', 'Түркмен'),
('tl', 'Tagalog', 'Wikang Tagalo'),
('tn', 'Tswana', 'Setswana'),
('to', 'Tonga', 'chiTonga'),
('tr', 'Turkish', 'Türkçe'),
('ts', 'Tsonga', 'Xitsonga'),
('tt', 'Tatar', 'татарча'),
('uk', 'Ukrainian', 'Українська'),
('ur', 'Urdu', 'اردو'),
('uz', 'Uzbek', 'O''zbek'),
('vi', 'Vietnamese', 'Tiếng Việt'),
('vo', 'Volapuk', 'Volapük'),
('wo', 'Wolof', 'Wolof'),
('xh', 'Xhosa', 'isiXhosa'),
('yo', 'Yoruba', 'Yorùbá'),
('zh', 'Chinese', '中文'),
('zu', 'Zulu', 'isiZulu');
